[tls]
  [[tls.certificates]]
    certFile = "/run/secrets/cert.crt"
    keyFile  = "/run/secrets/cert.key"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/run/secrets/cert.crt"
      keyFile  = "/run/secrets/cert.key"
